### PR TITLE
added Dockerfile to run and build application in a Docker

### PR DESCRIPTION
**Pull request by Alok255**

### CODE REVIEW

**Comment by rscipher001** [comment]
This is great for starting point and I think you should create a docker-compose file and create one more docker file for mysql

**Comment by Alok255** [comment]
> 
> 
> This is great for starting point and I think you should create a docker-compose file and create one more docker file for mysql

Added docker-compose, MySQL is already available as a docker image from the [docker hub MySQL page](https://hub.docker.com/_/mysql). You can just go and select the version you need from there.

**Comment by rscipher001** [comment]
> > 
> > 
> > This is great for starting point and I think you should create a docker-compose file and create one more docker file for mysql
> 
> Added docker-compose, MySQL is already available as a docker image from the [docker hub MySQL page](https://hub.docker.com/_/mysql). You can just go and select the ve


Okay fine, all we needed was a service in docker-compose.

Anyway optionally if you can update `README.md` with instructions on how to run docker then it would be great.

**Comment by Alok255** [comment]
> 
> 
> > > This is great for starting point and I think you should create a docker-compose file and create one more docker file for mysql
> > 
> > 
> > Added docker-compose, MySQL is already available as a docker image from the [docker hub MySQL page](https://hub.docker.com/_/mysql). You can just go and select the ve
> 
> Okay fine, all we needed was a service in docker-compose.
> 
> Anyway optionally if you can update `README.md` with instructions on how to run docker then it would be great.

Done: https://github.com/Alok255/todo-memory-app-spring-boot/blob/feature/Adding-Dockerfile/README.md#dockerising-spring-boot-application-with-mysql-database

**Pull request merged**
